dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
cache: pip

# Install
install:
  - python setup.py install

# Run
script:
  - pytest

# Deploy
# deploy:
#   provider: pypi
#   user: "Your username"
#   password: "Your password"
#   skip_existing: true
#   distributions: "sdist bdist_wheel" # Your distributions here
#   on:
#     tags: true